{% set reqfile = "requirements.txt" %}
{% set name = "pythae" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pythae-{{ version }}.tar.gz
  sha256: 191824894f1b49dc425dea4a53dc24491ebdbe22334298b4ac42e9f0b0726b09

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - dataclasses >=0.6
    - cloudpickle >=2.1.0
    - imageio
    - numpy >=1.19
    - pydantic >=2.0
    - scipy >=1.7.1
    - scikit-learn
    - pytorch >=1.10.1
    - tqdm
    - typing-extensions

test:
  imports:
    - pythae
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/clementchadebec/benchmark_VAE
  summary: Unifying Generative Autoencoders in Python
  license: Apache-2.0
  license_file: LICENSE
  description: |
    This library implements some of the most common (Variational) Autoencoder models. 
    In particular it provides the possibility to perform benchmark experiments and 
    comparisons by training the models with the same autoencoding neural network 
    architecture. The feature *make your own autoencoder* allows you to train any of 
    these models with your own data and own Encoder and Decoder neural networks.

    PyPI: [https://pypi.org/project/pythae](https://pypi.org/project/pythae)

  doc_url: https://pythae.readthedocs.io/en/latest/
  dev_url: https://github.com/clementchadebec/benchmark_VAE

extra:
  recipe-maintainers:
    - clementchadebec
    - sugatoray
